#!/usr/bin/env bash

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Use directory stack, assume I won't use more than 5
alias d='dirs -v'
alias d1='cd `dirs -l +1`'
alias d2='cd `dirs -l +2`'
alias d3='cd `dirs -l +3`'
alias d4='cd `dirs -l +4`'
alias d5='cd `dirs -l +5`'
alias +='pushd .'
alias _='popd'

# software specific
#alias kubectl='microk8s.kubectl'
#alias helm='microk8s.helm3'

# git
git config --global alias.gone "!f() { git fetch --all --prune; git branch -vv | awk '/: gone]/{print \$1}' | xargs git branch -D; }; f"
